version: '3.8'

services:
  db:
    image: postgres:13.0-alpine

    volumes:
      - /var/lib/postgresql/data/

    env_file:
      - ./.env

  web:
    image: tacostrophe/yad:latest

    restart: always

    ports:
     - "80:80"
    
    depends_on:
      - db

    env_file:
      - ./.env 
